import type { Collection, Paper } from "./types";

// Seed library — real, recognizable ML/RL papers (matches the design prototype).
// In a later phase this comes from the local SQLite database via Tauri commands.
export const PAPERS: Paper[] = [
  {
    id: "attention",
    title: "Attention Is All You Need",
    authors: "Vaswani et al.",
    authorsFull:
      "A. Vaswani, N. Shazeer, N. Parmar, J. Uszkoreit, L. Jones, A. N. Gomez, Ł. Kaiser, I. Polosukhin",
    year: 2017,
    venue: "NeurIPS",
    doi: "10.48550/arXiv.1706.03762",
    arxiv: "1706.03762",
    tags: ["Transformers", "NLP", "Attention"],
    read: true,
    fav: true,
    added: "2d ago",
    addedTs: 220,
    abstract:
      "We propose the Transformer, a model architecture relying entirely on an attention mechanism to draw global dependencies between input and output, dispensing with recurrence and convolutions entirely.",
    notes:
      "Core reference for the self-attention block. Revisit the positional encoding section before the reading group.",
    hl: [
      {
        text: "removes the recurrence and convolutions entirely",
        color: "#FBE38E",
        page: 2,
        note: "This is the whole thesis — purely attention-based.",
      },
      {
        text: "the approach generalizes well to other tasks",
        color: "#A6D2F4",
        page: 3,
        note: "",
      },
      {
        text: "Multi-head attention allows the model to jointly attend to information from different representation subspaces",
        color: "#A8E0A0",
        page: 4,
        note: "Key intuition for why heads help.",
      },
    ],
  },
  {
    id: "dqn",
    title: "Playing Atari with Deep Reinforcement Learning",
    authors: "Mnih et al.",
    authorsFull:
      "V. Mnih, K. Kavukcuoglu, D. Silver, A. Graves, I. Antonoglou, D. Wierstra, M. Riedmiller",
    year: 2013,
    venue: "NIPS Deep Learning Workshop",
    doi: "—",
    arxiv: "1312.5602",
    tags: ["RL", "Deep Learning", "Atari"],
    read: false,
    fav: false,
    added: "5d ago",
    addedTs: 215,
    abstract:
      "We present the first deep learning model to successfully learn control policies directly from high-dimensional sensory input using reinforcement learning, evaluated on seven Atari 2600 games.",
    notes: "",
    hl: [
      {
        text: "learn control policies directly from high-dimensional sensory input",
        color: "#FBE38E",
        page: 1,
        note: "End-to-end from pixels.",
      },
    ],
  },
  {
    id: "ppo",
    title: "Proximal Policy Optimization Algorithms",
    authors: "Schulman et al.",
    authorsFull: "J. Schulman, F. Wolski, P. Dhariwal, A. Radford, O. Klimov",
    year: 2017,
    venue: "arXiv",
    doi: "—",
    arxiv: "1707.06347",
    tags: ["RL", "Policy Gradient"],
    read: false,
    fav: true,
    added: "1w ago",
    addedTs: 208,
    abstract:
      "We propose a new family of policy gradient methods that alternate between sampling data and optimizing a surrogate objective using stochastic gradient ascent, with a clipped objective for stability.",
    notes: "",
    hl: [
      {
        text: "a clipped surrogate objective",
        color: "#D6B8F0",
        page: 3,
        note: "The clip is what makes it robust.",
      },
    ],
  },
  {
    id: "adam",
    title: "Adam: A Method for Stochastic Optimization",
    authors: "Kingma & Ba",
    authorsFull: "D. P. Kingma, J. Ba",
    year: 2015,
    venue: "ICLR",
    doi: "—",
    arxiv: "1412.6980",
    tags: ["Optimization"],
    read: true,
    fav: false,
    added: "1w ago",
    addedTs: 205,
    abstract:
      "We introduce Adam, an algorithm for first-order gradient-based optimization of stochastic objective functions based on adaptive estimates of lower-order moments.",
    notes: "",
    hl: [],
  },
  {
    id: "bert",
    title: "BERT: Pre-training of Deep Bidirectional Transformers",
    authors: "Devlin et al.",
    authorsFull: "J. Devlin, M.-W. Chang, K. Lee, K. Toutanova",
    year: 2019,
    venue: "NAACL",
    doi: "10.18653/v1/N19-1423",
    arxiv: "1810.04805",
    tags: ["NLP", "Pretraining", "Transformers"],
    read: true,
    fav: false,
    added: "2w ago",
    addedTs: 190,
    abstract:
      "We introduce BERT, designed to pre-train deep bidirectional representations from unlabeled text by jointly conditioning on both left and right context in all layers.",
    notes: "",
    hl: [
      {
        text: "deep bidirectional representations",
        color: "#A6D2F4",
        page: 1,
        note: "",
      },
    ],
  },
  {
    id: "gan",
    title: "Generative Adversarial Networks",
    authors: "Goodfellow et al.",
    authorsFull:
      "I. J. Goodfellow, J. Pouget-Abadie, M. Mirza, B. Xu, D. Warde-Farley, S. Ozair, A. Courville, Y. Bengio",
    year: 2014,
    venue: "NeurIPS",
    doi: "—",
    arxiv: "1406.2661",
    tags: ["Generative", "GAN"],
    read: false,
    fav: false,
    added: "3w ago",
    addedTs: 170,
    abstract:
      "We propose a framework for estimating generative models via an adversarial process, in which we simultaneously train a generative model G and a discriminative model D.",
    notes: "",
    hl: [],
  },
  {
    id: "resnet",
    title: "Deep Residual Learning for Image Recognition",
    authors: "He et al.",
    authorsFull: "K. He, X. Zhang, S. Ren, J. Sun",
    year: 2016,
    venue: "CVPR",
    doi: "10.1109/CVPR.2016.90",
    arxiv: "1512.03385",
    tags: ["Vision", "CNN"],
    read: true,
    fav: true,
    added: "1mo ago",
    addedTs: 150,
    abstract:
      "We present a residual learning framework to ease the training of networks that are substantially deeper than those used previously, reformulating layers as learning residual functions.",
    notes: "Use for the depth-vs-accuracy slide.",
    hl: [
      {
        text: "reformulating layers as learning residual functions",
        color: "#A8E0A0",
        page: 2,
        note: "",
      },
    ],
  },
  {
    id: "dropout",
    title: "Dropout: A Simple Way to Prevent Neural Networks from Overfitting",
    authors: "Srivastava et al.",
    authorsFull:
      "N. Srivastava, G. Hinton, A. Krizhevsky, I. Sutskever, R. Salakhutdinov",
    year: 2014,
    venue: "JMLR",
    doi: "—",
    arxiv: "—",
    tags: ["Regularization"],
    read: false,
    fav: false,
    added: "1mo ago",
    addedTs: 140,
    abstract:
      "Dropout is a technique for addressing overfitting by randomly dropping units along with their connections from the neural network during training.",
    notes: "",
    hl: [],
  },
  {
    id: "sac",
    title: "Soft Actor-Critic",
    authors: "Haarnoja et al.",
    authorsFull: "T. Haarnoja, A. Zhou, P. Abbeel, S. Levine",
    year: 2018,
    venue: "ICML",
    doi: "—",
    arxiv: "1801.01290",
    tags: ["RL", "Off-Policy"],
    read: false,
    fav: false,
    added: "1mo ago",
    addedTs: 135,
    abstract:
      "We propose soft actor-critic, an off-policy actor-critic deep RL algorithm based on the maximum entropy framework, balancing exploration and exploitation via entropy maximization.",
    notes: "",
    hl: [],
  },
  {
    id: "alphago",
    title: "Mastering the Game of Go with Deep Neural Networks and Tree Search",
    authors: "Silver et al.",
    authorsFull: "D. Silver, A. Huang, C. J. Maddison, A. Guez, L. Sifre, et al.",
    year: 2016,
    venue: "Nature",
    doi: "10.1038/nature16961",
    arxiv: "—",
    tags: ["RL", "Search", "Games"],
    read: true,
    fav: true,
    added: "2mo ago",
    addedTs: 110,
    abstract:
      "We introduce a new approach to computer Go that uses value networks to evaluate board positions and policy networks to select moves, combined with Monte Carlo tree search.",
    notes: "",
    hl: [
      {
        text: "value networks to evaluate board positions and policy networks to select moves",
        color: "#FBE38E",
        page: 1,
        note: "Two-network decomposition.",
      },
    ],
  },
  {
    id: "vae",
    title: "Auto-Encoding Variational Bayes",
    authors: "Kingma & Welling",
    authorsFull: "D. P. Kingma, M. Welling",
    year: 2014,
    venue: "ICLR",
    doi: "—",
    arxiv: "1312.6114",
    tags: ["Generative", "VAE"],
    read: false,
    fav: false,
    added: "2mo ago",
    addedTs: 100,
    abstract:
      "We introduce a stochastic variational inference and learning algorithm that scales to large datasets and works with intractable posterior distributions, using a reparameterization of the variational lower bound.",
    notes: "",
    hl: [],
  },
  {
    id: "batchnorm",
    title: "Batch Normalization: Accelerating Deep Network Training",
    authors: "Ioffe & Szegedy",
    authorsFull: "S. Ioffe, C. Szegedy",
    year: 2015,
    venue: "ICML",
    doi: "—",
    arxiv: "1502.03167",
    tags: ["Optimization"],
    read: true,
    fav: false,
    added: "3mo ago",
    addedTs: 80,
    abstract:
      "We address internal covariate shift by normalizing layer inputs for each training mini-batch, allowing higher learning rates and reducing sensitivity to initialization.",
    notes: "",
    hl: [],
  },
  {
    id: "gpt3",
    title: "Language Models are Few-Shot Learners",
    authors: "Brown et al.",
    authorsFull: "T. B. Brown, B. Mann, N. Ryder, M. Subbiah, et al.",
    year: 2020,
    venue: "NeurIPS",
    doi: "—",
    arxiv: "2005.14165",
    tags: ["NLP", "LLM"],
    read: false,
    fav: true,
    added: "3mo ago",
    addedTs: 70,
    abstract:
      "We show that scaling up language models greatly improves task-agnostic, few-shot performance, sometimes reaching competitiveness with prior fine-tuning approaches.",
    notes: "",
    hl: [
      {
        text: "task-agnostic, few-shot performance",
        color: "#D6B8F0",
        page: 2,
        note: "In-context learning emerges with scale.",
      },
    ],
  },
  {
    id: "ddpg",
    title: "Continuous Control with Deep Reinforcement Learning",
    authors: "Lillicrap et al.",
    authorsFull: "T. P. Lillicrap, J. J. Hunt, A. Pritzel, N. Heess, et al.",
    year: 2016,
    venue: "ICLR",
    doi: "—",
    arxiv: "1509.02971",
    tags: ["RL", "Continuous"],
    read: false,
    fav: false,
    added: "4mo ago",
    addedTs: 50,
    abstract:
      "We adapt the ideas underlying the success of deep Q-learning to the continuous action domain, presenting an actor-critic, model-free algorithm based on the deterministic policy gradient.",
    notes: "",
    hl: [],
  },
];

export const COLLECTIONS: Collection[] = [
  {
    id: "col-thesis",
    name: "Thesis — Sequence Models",
    color: "#4B57D6",
    indent: "0",
    ids: ["attention", "bert", "gpt3"],
  },
  {
    id: "col-rl",
    name: "RL Reading Group",
    color: "#2E9E6B",
    indent: "0",
    ids: ["dqn", "ppo", "sac", "alphago", "ddpg"],
  },
  {
    id: "col-rl-sub",
    name: "↳ Policy Gradient",
    color: "#E0A23A",
    indent: "14px",
    ids: ["ppo", "sac"],
  },
  {
    id: "col-gen",
    name: "Generative Models",
    color: "#C0395E",
    indent: "0",
    ids: ["gan", "vae"],
  },
];

export const HL_PALETTE = [
  { name: "Yellow", color: "#FBE38E" },
  { name: "Green", color: "#A8E0A0" },
  { name: "Blue", color: "#A6D2F4" },
  { name: "Pink", color: "#F4B3C7" },
  { name: "Purple", color: "#D6B8F0" },
];

export const CITE_STYLE_FULL: Record<string, string> = {
  APA: "APA 7th edition",
  MLA: "MLA 9th edition",
  Chicago: "Chicago 17th (author-date)",
  BibTeX: "BibTeX entry",
};

export const WATCH_FOLDERS = ["~/Downloads/Papers", "~/Dropbox/Zotero-inbox"];

export const PALETTE_FILTERS = [
  "author:",
  "year:2017",
  "tag:RL",
  "venue:NeurIPS",
  "in:abstract",
];
